### ISSUE TITLE
Didn't work with toybox's feat multiplier 

### ISSUE THREAD

**Issue by mysq1isworst** [microsoftenator2022/AlternateHumanTraits#1]
use this feature with this mods, I can't get any benefits. no bonus feats no traits.
pls fix it.

**Comment by aaronmaslen** [comment]
1. I cannot and will not provide support for other mods unless explicitly stated otherwise.
2. Each trait *requires and replaces* either humans' bonus feat or the Skilled trait. This mod already allows you to make as many selections as is possible.
3. Toybox's "Feature Selection Multiplier" does not allow you to ignore prerequisites. If you want to do that, use the "Ignore Feat Restrictions" option.
4. Also make sure that you have "Enable 'next' when no feats selections are available" ticked in Toybox if you're using the Feature Selection Multiplier
